/*
 * generated by Xtext
 */
package ar.edu.unq.ui.contentassist

import ar.edu.unq.ui.contentassist.AbstractXtGobstonesProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class XtGobstonesProposalProvider extends AbstractXtGobstonesProposalProvider {
}
