/*
 * generated by Xtext
 */
package ar.edu.unq;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class XtGobstonesRuntimeModule extends ar.edu.unq.AbstractXtGobstonesRuntimeModule {

}
