/*
 * generated by Xtext
 */
package ar.edu.unq;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class XtGobstonesStandaloneSetup extends XtGobstonesStandaloneSetupGenerated{

	public static void doSetup() {
		new XtGobstonesStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

